/*
 * This source file was generated by the Gradle 'init' task
 */
package studentmanager;

public class App {
    public String getGreeting() {
        return "Hello and welcome to the Student Manager Application, Admin!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StudentManager studentManager = new StudentManager(); // constructor runs here, dummy records loaded
        studentManager.mainMenu();
    }
}
